import type { FormComboBoxOption } from "@/types/types";

export const COUNTRY_IDS: FormComboBoxOption[] = [
    { "value": "1", "displayLabel": "Afganistán", "optionLabel": "Afganistán", "searchTerm": "Afganistán" },
    { "value": "2", "displayLabel": "Albania", "optionLabel": "Albania", "searchTerm": "Albania" },
    { "value": "3", "displayLabel": "Alemania", "optionLabel": "Alemania", "searchTerm": "Alemania" },
    { "value": "4", "displayLabel": "Andorra", "optionLabel": "Andorra", "searchTerm": "Andorra" },
    { "value": "5", "displayLabel": "Angola", "optionLabel": "Angola", "searchTerm": "Angola" },
    { "value": "6", "displayLabel": "Anguilla (RU)", "optionLabel": "Anguilla (RU)", "searchTerm": "Anguilla (RU)" },
    { "value": "7", "displayLabel": "Antártida", "optionLabel": "Antártida", "searchTerm": "Antártida" },
    { "value": "8", "displayLabel": "Antigua y Barbuda", "optionLabel": "Antigua y Barbuda", "searchTerm": "Antigua y Barbuda" },
    { "value": "9", "displayLabel": "Arabia Saudita", "optionLabel": "Arabia Saudita", "searchTerm": "Arabia Saudita" },
    { "value": "10", "displayLabel": "Archipiélago Svalbard (Noruega)", "optionLabel": "Archipiélago Svalbard (Noruega)", "searchTerm": "Archipiélago Svalbard (Noruega)" },
    { "value": "11", "displayLabel": "Argelia", "optionLabel": "Argelia", "searchTerm": "Argelia" },
    { "value": "12", "displayLabel": "Argentina", "optionLabel": "Argentina", "searchTerm": "Argentina" },
    { "value": "13", "displayLabel": "Armenia", "optionLabel": "Armenia", "searchTerm": "Armenia" },
    { "value": "14", "displayLabel": "Aruba (Paises Bajos)", "optionLabel": "Aruba (Paises Bajos)", "searchTerm": "Aruba (Paises Bajos)" },
    { "value": "15", "displayLabel": "Atolón Johnston (EEUU)", "optionLabel": "Atolón Johnston (EEUU)", "searchTerm": "Atolón Johnston (EEUU)" },
    { "value": "16", "displayLabel": "Australia", "optionLabel": "Australia", "searchTerm": "Australia" },
    { "value": "17", "displayLabel": "Austria", "optionLabel": "Austria", "searchTerm": "Austria" },
    { "value": "18", "displayLabel": "Azerbaiyán", "optionLabel": "Azerbaiyán", "searchTerm": "Azerbaiyán" },
    { "value": "19", "displayLabel": "Bahamas", "optionLabel": "Bahamas", "searchTerm": "Bahamas" },
    { "value": "20", "displayLabel": "Bahrein", "optionLabel": "Bahrein", "searchTerm": "Bahrein" },
    { "value": "21", "displayLabel": "Bangladesh", "optionLabel": "Bangladesh", "searchTerm": "Bangladesh" },
    { "value": "22", "displayLabel": "Barbados", "optionLabel": "Barbados", "searchTerm": "Barbados" },
    { "value": "23", "displayLabel": "Belarús", "optionLabel": "Belarús", "searchTerm": "Belarús" },
    { "value": "24", "displayLabel": "Bélgica", "optionLabel": "Bélgica", "searchTerm": "Bélgica" },
    { "value": "25", "displayLabel": "Belice", "optionLabel": "Belice", "searchTerm": "Belice" },
    { "value": "26", "displayLabel": "Benin", "optionLabel": "Benin", "searchTerm": "Benin" },
    { "value": "27", "displayLabel": "Bermudas (RU)", "optionLabel": "Bermudas (RU)", "searchTerm": "Bermudas (RU)" },
    { "value": "28", "displayLabel": "Bolivia", "optionLabel": "Bolivia", "searchTerm": "Bolivia" },
    { "value": "29", "displayLabel": "Bonaire (Paises Bajos)", "optionLabel": "Bonaire (Paises Bajos)", "searchTerm": "Bonaire (Paises Bajos)" },
    { "value": "30", "displayLabel": "Bosnia y Herzegovina", "optionLabel": "Bosnia y Herzegovina", "searchTerm": "Bosnia y Herzegovina" },
    { "value": "31", "displayLabel": "Botswana", "optionLabel": "Botswana", "searchTerm": "Botswana" },
    { "value": "32", "displayLabel": "Brasil", "optionLabel": "Brasil", "searchTerm": "Brasil" },
    { "value": "33", "displayLabel": "Brunei", "optionLabel": "Brunei", "searchTerm": "Brunei" },
    { "value": "34", "displayLabel": "Bulgaria", "optionLabel": "Bulgaria", "searchTerm": "Bulgaria" },
    { "value": "35", "displayLabel": "Burkina Faso", "optionLabel": "Burkina Faso", "searchTerm": "Burkina Faso" },
    { "value": "36", "displayLabel": "Burundi", "optionLabel": "Burundi", "searchTerm": "Burundi" },
    { "value": "37", "displayLabel": "Bután", "optionLabel": "Bután", "searchTerm": "Bután" },
    { "value": "38", "displayLabel": "Cabo Verde", "optionLabel": "Cabo Verde", "searchTerm": "Cabo Verde" },
    { "value": "39", "displayLabel": "Cambodia", "optionLabel": "Cambodia", "searchTerm": "Cambodia" },
    { "value": "40", "displayLabel": "Camerún", "optionLabel": "Camerún", "searchTerm": "Camerún" },
    { "value": "41", "displayLabel": "Canadá", "optionLabel": "Canadá", "searchTerm": "Canadá" },
    { "value": "42", "displayLabel": "Catar", "optionLabel": "Catar", "searchTerm": "Catar" },
    { "value": "43", "displayLabel": "Chad", "optionLabel": "Chad", "searchTerm": "Chad" },
    { "value": "44", "displayLabel": "Chile", "optionLabel": "Chile", "searchTerm": "Chile" },
    { "value": "45", "displayLabel": "China", "optionLabel": "China", "searchTerm": "China" },
    { "value": "46", "displayLabel": "Chipre", "optionLabel": "Chipre", "searchTerm": "Chipre" },
    { "value": "47", "displayLabel": "Colombia", "optionLabel": "Colombia", "searchTerm": "Colombia" },
    { "value": "48", "displayLabel": "Comoras", "optionLabel": "Comoras", "searchTerm": "Comoras" },
    { "value": "49", "displayLabel": "Congo", "optionLabel": "Congo", "searchTerm": "Congo" },
    { "value": "50", "displayLabel": "Costa de Marfil", "optionLabel": "Costa de Marfil", "searchTerm": "Costa de Marfil" },
    { "value": "51", "displayLabel": "Costa Rica", "optionLabel": "Costa Rica", "searchTerm": "Costa Rica" },
    { "value": "52", "displayLabel": "Croacia", "optionLabel": "Croacia", "searchTerm": "Croacia" },
    { "value": "53", "displayLabel": "Cuba", "optionLabel": "Cuba", "searchTerm": "Cuba" },
    { "value": "54", "displayLabel": "Curazao (Paises Bajos)", "optionLabel": "Curazao (Paises Bajos)", "searchTerm": "Curazao (Paises Bajos)" },
    { "value": "55", "displayLabel": "Dinamarca", "optionLabel": "Dinamarca", "searchTerm": "Dinamarca" },
    { "value": "56", "displayLabel": "Dominica", "optionLabel": "Dominica", "searchTerm": "Dominica" },
    { "value": "57", "displayLabel": "Ecuador", "optionLabel": "Ecuador", "searchTerm": "Ecuador" },
    { "value": "58", "displayLabel": "Egipto", "optionLabel": "Egipto", "searchTerm": "Egipto" },
    { "value": "59", "displayLabel": "El Salvador", "optionLabel": "El Salvador", "searchTerm": "El Salvador" },
    { "value": "60", "displayLabel": "Emiratos Árabes Unidos", "optionLabel": "Emiratos Árabes Unidos", "searchTerm": "Emiratos Árabes Unidos" },
    { "value": "61", "displayLabel": "Eritrea", "optionLabel": "Eritrea", "searchTerm": "Eritrea" },
    { "value": "62", "displayLabel": "Eslovaquia", "optionLabel": "Eslovaquia", "searchTerm": "Eslovaquia" },
    { "value": "63", "displayLabel": "Eslovenia", "optionLabel": "Eslovenia", "searchTerm": "Eslovenia" },
    { "value": "64", "displayLabel": "España", "optionLabel": "España", "searchTerm": "España" },
    { "value": "65", "displayLabel": "Estados Federados de Micronesia", "optionLabel": "Estados Federados de Micronesia", "searchTerm": "Estados Federados de Micronesia" },
    { "value": "66", "displayLabel": "Estados Unidos", "optionLabel": "Estados Unidos", "searchTerm": "Estados Unidos" },
    { "value": "67", "displayLabel": "Estonia", "optionLabel": "Estonia", "searchTerm": "Estonia" },
    { "value": "68", "displayLabel": "Etiopía", "optionLabel": "Etiopía", "searchTerm": "Etiopía" },
    { "value": "69", "displayLabel": "Fiji", "optionLabel": "Fiji", "searchTerm": "Fiji" },
    { "value": "70", "displayLabel": "Filipinas", "optionLabel": "Filipinas", "searchTerm": "Filipinas" },
    { "value": "71", "displayLabel": "Finlandia", "optionLabel": "Finlandia", "searchTerm": "Finlandia" },
    { "value": "72", "displayLabel": "Francia", "optionLabel": "Francia", "searchTerm": "Francia" },
    { "value": "73", "displayLabel": "Gabón", "optionLabel": "Gabón", "searchTerm": "Gabón" },
    { "value": "74", "displayLabel": "Gambia", "optionLabel": "Gambia", "searchTerm": "Gambia" },
    { "value": "75", "displayLabel": "Georgia", "optionLabel": "Georgia", "searchTerm": "Georgia" },
    { "value": "76", "displayLabel": "Ghana", "optionLabel": "Ghana", "searchTerm": "Ghana" },
    { "value": "77", "displayLabel": "Gibraltar (RU)", "optionLabel": "Gibraltar (RU)", "searchTerm": "Gibraltar (RU)" },
    { "value": "78", "displayLabel": "Granada", "optionLabel": "Granada", "searchTerm": "Granada" },
    { "value": "79", "displayLabel": "Grecia", "optionLabel": "Grecia", "searchTerm": "Grecia" },
    { "value": "80", "displayLabel": "Groenlandia (Dinamarca)", "optionLabel": "Groenlandia (Dinamarca)", "searchTerm": "Groenlandia (Dinamarca)" },
    { "value": "81", "displayLabel": "Guadalupe (Francia)", "optionLabel": "Guadalupe (Francia)", "searchTerm": "Guadalupe (Francia)" },
    { "value": "82", "displayLabel": "Guam (EEUU)", "optionLabel": "Guam (EEUU)", "searchTerm": "Guam (EEUU)" },
    { "value": "83", "displayLabel": "Guatemala", "optionLabel": "Guatemala", "searchTerm": "Guatemala" },
    { "value": "84", "displayLabel": "Guayana Francesa (Francia)", "optionLabel": "Guayana Francesa (Francia)", "searchTerm": "Guayana Francesa (Francia)" },
    { "value": "85", "displayLabel": "Guernsey (RU)", "optionLabel": "Guernsey (RU)", "searchTerm": "Guernsey (RU)" },
    { "value": "86", "displayLabel": "Guinea", "optionLabel": "Guinea", "searchTerm": "Guinea" },
    { "value": "87", "displayLabel": "Guinea-Bissau", "optionLabel": "Guinea-Bissau", "searchTerm": "Guinea-Bissau" },
    { "value": "88", "displayLabel": "Guinea Ecuatorial", "optionLabel": "Guinea Ecuatorial", "searchTerm": "Guinea Ecuatorial" },
    { "value": "89", "displayLabel": "Guyana", "optionLabel": "Guyana", "searchTerm": "Guyana" },
    { "value": "90", "displayLabel": "Haiti", "optionLabel": "Haiti", "searchTerm": "Haiti" },
    { "value": "91", "displayLabel": "Honduras", "optionLabel": "Honduras", "searchTerm": "Honduras" },
    { "value": "92", "displayLabel": "Hungría", "optionLabel": "Hungría", "searchTerm": "Hungría" },
    { "value": "93", "displayLabel": "India", "optionLabel": "India", "searchTerm": "India" },
    { "value": "94", "displayLabel": "Indonesia", "optionLabel": "Indonesia", "searchTerm": "Indonesia" },
    { "value": "95", "displayLabel": "Iran", "optionLabel": "Iran", "searchTerm": "Iran" },
    { "value": "96", "displayLabel": "Iraq", "optionLabel": "Iraq", "searchTerm": "Iraq" },
    { "value": "97", "displayLabel": "Irlanda", "optionLabel": "Irlanda", "searchTerm": "Irlanda" },
    { "value": "98", "displayLabel": "Isla Baker (EEUU)", "optionLabel": "Isla Baker (EEUU)", "searchTerm": "Isla Baker (EEUU)" },
    { "value": "99", "displayLabel": "Isla Bouvet (Noruega)", "optionLabel": "Isla Bouvet (Noruega)", "searchTerm": "Isla Bouvet (Noruega)" },
    { "value": "100", "displayLabel": "Isla Christmas (Australia)", "optionLabel": "Isla Christmas (Australia)", "searchTerm": "Isla Christmas (Australia)" },
    { "value": "101", "displayLabel": "Isla de Man (RU)", "optionLabel": "Isla de Man (RU)", "searchTerm": "Isla de Man (RU)" },
    { "value": "102", "displayLabel": "Isla Howland (EEUU)", "optionLabel": "Isla Howland (EEUU)", "searchTerm": "Isla Howland (EEUU)" },
    { "value": "103", "displayLabel": "Isla Jarvis (EEUU)", "optionLabel": "Isla Jarvis (EEUU)", "searchTerm": "Isla Jarvis (EEUU)" },
    { "value": "104", "displayLabel": "Isla Juan De Nova (Francia)", "optionLabel": "Isla Juan De Nova (Francia)", "searchTerm": "Isla Juan De Nova (Francia)" },
    { "value": "105", "displayLabel": "Isla Midway (EEUU)", "optionLabel": "Isla Midway (EEUU)", "searchTerm": "Isla Midway (EEUU)" },
    { "value": "106", "displayLabel": "Islandia", "optionLabel": "Islandia", "searchTerm": "Islandia" },
    { "value": "107", "displayLabel": "Isla Norfolk (Australia)", "optionLabel": "Isla Norfolk (Australia)", "searchTerm": "Isla Norfolk (Australia)" },
    { "value": "108", "displayLabel": "Islas Caimán (RU)", "optionLabel": "Islas Caimán (RU)", "searchTerm": "Islas Caimán (RU)" },
    { "value": "109", "displayLabel": "Islas Cocos (Australia)", "optionLabel": "Islas Cocos (Australia)", "searchTerm": "Islas Cocos (Australia)" },
    { "value": "110", "displayLabel": "Islas Cook (Nueva Zelanda)", "optionLabel": "Islas Cook (Nueva Zelanda)", "searchTerm": "Islas Cook (Nueva Zelanda)" },
    { "value": "111", "displayLabel": "Islas Faroe (Dinamarca)", "optionLabel": "Islas Faroe (Dinamarca)", "searchTerm": "Islas Faroe (Dinamarca)" },
    { "value": "112", "displayLabel": "Islas Georgias del Sur y Sandwich del Sur (RU)", "optionLabel": "Islas Georgias del Sur y Sandwich del Sur (RU)", "searchTerm": "Islas Georgias del Sur y Sandwich del Sur (RU)" },
    { "value": "113", "displayLabel": "Islas Gloriosas (Francia)", "optionLabel": "Islas Gloriosas (Francia)", "searchTerm": "Islas Gloriosas (Francia)" },
    { "value": "114", "displayLabel": "Islas Heard y McDonald (Australia)", "optionLabel": "Islas Heard y McDonald (Australia)", "searchTerm": "Islas Heard y McDonald (Australia)" },
    { "value": "115", "displayLabel": "Islas Malvinas (RU)", "optionLabel": "Islas Malvinas (RU)", "searchTerm": "Islas Malvinas (RU)" },
    { "value": "116", "displayLabel": "Islas Marianas del Norte (EEUU)", "optionLabel": "Islas Marianas del Norte (EEUU)", "searchTerm": "Islas Marianas del Norte (EEUU)" },
    { "value": "117", "displayLabel": "Islas Marshall", "optionLabel": "Islas Marshall", "searchTerm": "Islas Marshall" },
    { "value": "118", "displayLabel": "Islas Paracel (China)", "optionLabel": "Islas Paracel (China)", "searchTerm": "Islas Paracel (China)" },
    { "value": "119", "displayLabel": "Islas Pitcairn (RU)", "optionLabel": "Islas Pitcairn (RU)", "searchTerm": "Islas Pitcairn (RU)" },
    { "value": "120", "displayLabel": "Islas Salomón", "optionLabel": "Islas Salomón", "searchTerm": "Islas Salomón" },
    { "value": "121", "displayLabel": "Islas Spratly (en disputa)", "optionLabel": "Islas Spratly (en disputa)", "searchTerm": "Islas Spratly (en disputa)" },
    { "value": "122", "displayLabel": "Islas Vírgenes Británicas (RU)", "optionLabel": "Islas Vírgenes Británicas (RU)", "searchTerm": "Islas Vírgenes Británicas (RU)" },
    { "value": "123", "displayLabel": "Islas Vírgenes Estadounidenses (EEUU)", "optionLabel": "Islas Vírgenes Estadounidenses (EEUU)", "searchTerm": "Islas Vírgenes Estadounidenses (EEUU)" },
    { "value": "124", "displayLabel": "Isla Wake (EEUU)", "optionLabel": "Isla Wake (EEUU)", "searchTerm": "Isla Wake (EEUU)" },
    { "value": "125", "displayLabel": "Israel", "optionLabel": "Israel", "searchTerm": "Israel" },
    { "value": "126", "displayLabel": "Italia", "optionLabel": "Italia", "searchTerm": "Italia" },
    { "value": "127", "displayLabel": "Jamaica", "optionLabel": "Jamaica", "searchTerm": "Jamaica" },
    { "value": "128", "displayLabel": "Jan Mayen (Norway)", "optionLabel": "Jan Mayen (Norway)", "searchTerm": "Jan Mayen (Norway)" },
    { "value": "129", "displayLabel": "Japón", "optionLabel": "Japón", "searchTerm": "Japón" },
    { "value": "130", "displayLabel": "Jersey (RU)", "optionLabel": "Jersey (RU)", "searchTerm": "Jersey (RU)" },
    { "value": "131", "displayLabel": "Jordania", "optionLabel": "Jordania", "searchTerm": "Jordania" },
    { "value": "132", "displayLabel": "Kazakistán", "optionLabel": "Kazakistán", "searchTerm": "Kazakistán" },
    { "value": "133", "displayLabel": "Kenya", "optionLabel": "Kenya", "searchTerm": "Kenya" },
    { "value": "134", "displayLabel": "Kirguistán", "optionLabel": "Kirguistán", "searchTerm": "Kirguistán" },
    { "value": "135", "displayLabel": "Kiribati", "optionLabel": "Kiribati", "searchTerm": "Kiribati" },
    { "value": "136", "displayLabel": "Kuwait", "optionLabel": "Kuwait", "searchTerm": "Kuwait" },
    { "value": "137", "displayLabel": "Laos", "optionLabel": "Laos", "searchTerm": "Laos" },
    { "value": "138", "displayLabel": "Lesotho", "optionLabel": "Lesotho", "searchTerm": "Lesotho" },
    { "value": "139", "displayLabel": "Letonia", "optionLabel": "Letonia", "searchTerm": "Letonia" },
    { "value": "140", "displayLabel": "Líbano", "optionLabel": "Líbano", "searchTerm": "Líbano" },
    { "value": "141", "displayLabel": "Liberia", "optionLabel": "Liberia", "searchTerm": "Liberia" },
    { "value": "142", "displayLabel": "Libia", "optionLabel": "Libia", "searchTerm": "Libia" },
    { "value": "143", "displayLabel": "Liechtenstein", "optionLabel": "Liechtenstein", "searchTerm": "Liechtenstein" },
    { "value": "144", "displayLabel": "Lituania", "optionLabel": "Lituania", "searchTerm": "Lituania" },
    { "value": "145", "displayLabel": "Luxemburgo", "optionLabel": "Luxemburgo", "searchTerm": "Luxemburgo" },
    { "value": "146", "displayLabel": "Macedonia", "optionLabel": "Macedonia", "searchTerm": "Macedonia" },
    { "value": "147", "displayLabel": "Madagascar", "optionLabel": "Madagascar", "searchTerm": "Madagascar" },
    { "value": "148", "displayLabel": "Malasia", "optionLabel": "Malasia", "searchTerm": "Malasia" },
    { "value": "149", "displayLabel": "Malawi", "optionLabel": "Malawi", "searchTerm": "Malawi" },
    { "value": "150", "displayLabel": "Maldivas", "optionLabel": "Maldivas", "searchTerm": "Maldivas" },
    { "value": "151", "displayLabel": "Mali", "optionLabel": "Mali", "searchTerm": "Mali" },
    { "value": "152", "displayLabel": "Malta", "optionLabel": "Malta", "searchTerm": "Malta" },
    { "value": "153", "displayLabel": "Marruecos", "optionLabel": "Marruecos", "searchTerm": "Marruecos" },
    { "value": "154", "displayLabel": "Martinica (Francia)", "optionLabel": "Martinica (Francia)", "searchTerm": "Martinica (Francia)" },
    { "value": "155", "displayLabel": "Mauricio", "optionLabel": "Mauricio", "searchTerm": "Mauricio" },
    { "value": "156", "displayLabel": "Mauritania", "optionLabel": "Mauritania", "searchTerm": "Mauritania" },
    { "value": "157", "displayLabel": "Mayotte (Francia)", "optionLabel": "Mayotte (Francia)", "searchTerm": "Mayotte (Francia)" },
    { "value": "158", "displayLabel": "México", "optionLabel": "México", "searchTerm": "México" },
    { "value": "159", "displayLabel": "Moldavia", "optionLabel": "Moldavia", "searchTerm": "Moldavia" },
    { "value": "160", "displayLabel": "Mónaco", "optionLabel": "Mónaco", "searchTerm": "Mónaco" },
    { "value": "161", "displayLabel": "Mongolia", "optionLabel": "Mongolia", "searchTerm": "Mongolia" },
    { "value": "162", "displayLabel": "Montenegro", "optionLabel": "Montenegro", "searchTerm": "Montenegro" },
    { "value": "163", "displayLabel": "Montserrat (RU)", "optionLabel": "Montserrat (RU)", "searchTerm": "Montserrat (RU)" },
    { "value": "164", "displayLabel": "Mozambique", "optionLabel": "Mozambique", "searchTerm": "Mozambique" },
    { "value": "165", "displayLabel": "Myanmar", "optionLabel": "Myanmar", "searchTerm": "Myanmar" },
    { "value": "166", "displayLabel": "Namibia", "optionLabel": "Namibia", "searchTerm": "Namibia" },
    { "value": "167", "displayLabel": "Naurú", "optionLabel": "Naurú", "searchTerm": "Naurú" },
    { "value": "168", "displayLabel": "Nepal", "optionLabel": "Nepal", "searchTerm": "Nepal" },
    { "value": "169", "displayLabel": "Nicaragua", "optionLabel": "Nicaragua", "searchTerm": "Nicaragua" },
    { "value": "170", "displayLabel": "Níger", "optionLabel": "Níger", "searchTerm": "Níger" },
    { "value": "171", "displayLabel": "Nigeria", "optionLabel": "Nigeria", "searchTerm": "Nigeria" },
    { "value": "172", "displayLabel": "Niue (Nueva Zelanda)", "optionLabel": "Niue (Nueva Zelanda)", "searchTerm": "Niue (Nueva Zelanda)" },
    { "value": "173", "displayLabel": "Noruega", "optionLabel": "Noruega", "searchTerm": "Noruega" },
    { "value": "174", "displayLabel": "Nueva Caledonia (Francia)", "optionLabel": "Nueva Caledonia (Francia)", "searchTerm": "Nueva Caledonia (Francia)" },
    { "value": "175", "displayLabel": "Nueva Zelanda", "optionLabel": "Nueva Zelanda", "searchTerm": "Nueva Zelanda" },
    { "value": "176", "displayLabel": "Omán", "optionLabel": "Omán", "searchTerm": "Omán" },
    { "value": "177", "displayLabel": "Paises Bajos", "optionLabel": "Paises Bajos", "searchTerm": "Paises Bajos" },
    { "value": "178", "displayLabel": "Pakistán", "optionLabel": "Pakistán", "searchTerm": "Pakistán" },
    { "value": "179", "displayLabel": "Palau (EEUU)", "optionLabel": "Palau (EEUU)", "searchTerm": "Palau (EEUU)" },
    { "value": "180", "displayLabel": "Palestina", "optionLabel": "Palestina", "searchTerm": "Palestina" },
    { "value": "181", "displayLabel": "Panamá", "optionLabel": "Panamá", "searchTerm": "Panamá" },
    { "value": "182", "displayLabel": "Papúa Nueva Guinea", "optionLabel": "Papúa Nueva Guinea", "searchTerm": "Papúa Nueva Guinea" },
    { "value": "183", "displayLabel": "Paraguay", "optionLabel": "Paraguay", "searchTerm": "Paraguay" },
    { "value": "184", "displayLabel": "Perú", "optionLabel": "Perú", "searchTerm": "Perú" },
    { "value": "185", "displayLabel": "Polinesia Francesa (Francia)", "optionLabel": "Polinesia Francesa (Francia)", "searchTerm": "Polinesia Francesa (Francia)" },
    { "value": "186", "displayLabel": "Polonia", "optionLabel": "Polonia", "searchTerm": "Polonia" },
    { "value": "187", "displayLabel": "Portugal", "optionLabel": "Portugal", "searchTerm": "Portugal" },
    { "value": "188", "displayLabel": "Puerto Rico (EEUU)", "optionLabel": "Puerto Rico (EEUU)", "searchTerm": "Puerto Rico (EEUU)" },
    { "value": "189", "displayLabel": "Reino Unido", "optionLabel": "Reino Unido", "searchTerm": "Reino Unido" },
    { "value": "190", "displayLabel": "República Centroafricana", "optionLabel": "República Centroafricana", "searchTerm": "República Centroafricana" },
    { "value": "191", "displayLabel": "República Checa", "optionLabel": "República Checa", "searchTerm": "República Checa" },
    { "value": "192", "displayLabel": "República de Corea", "optionLabel": "República de Corea", "searchTerm": "República de Corea" },
    { "value": "193", "displayLabel": "República Democrática del Congo", "optionLabel": "República Democrática del Congo", "searchTerm": "República Democrática del Congo" },
    { "value": "194", "displayLabel": "República Dominicana", "optionLabel": "República Dominicana", "searchTerm": "República Dominicana" },
    { "value": "195", "displayLabel": "Reunión (Francia)", "optionLabel": "Reunión (Francia)", "searchTerm": "Reunión (Francia)" },
    { "value": "196", "displayLabel": "RPD Corea", "optionLabel": "RPD Corea", "searchTerm": "RPD Corea" },
    { "value": "197", "displayLabel": "Ruanda", "optionLabel": "Ruanda", "searchTerm": "Ruanda" },
    { "value": "198", "displayLabel": "Rumania", "optionLabel": "Rumania", "searchTerm": "Rumania" },
    { "value": "199", "displayLabel": "Rusia", "optionLabel": "Rusia", "searchTerm": "Rusia" },
    { "value": "200", "displayLabel": "Sahara Occidental", "optionLabel": "Sahara Occidental", "searchTerm": "Sahara Occidental" },
    { "value": "201", "displayLabel": "Samoa", "optionLabel": "Samoa", "searchTerm": "Samoa" },
    { "value": "202", "displayLabel": "Samoa Americana (EEUU)", "optionLabel": "Samoa Americana (EEUU)", "searchTerm": "Samoa Americana (EEUU)" },
    { "value": "203", "displayLabel": "San Cristóbal y Nieves", "optionLabel": "San Cristóbal y Nieves", "searchTerm": "San Cristóbal y Nieves" },
    { "value": "204", "displayLabel": "San Marino", "optionLabel": "San Marino", "searchTerm": "San Marino" },
    { "value": "205", "displayLabel": "San Pedro y Miquelón (Francia)", "optionLabel": "San Pedro y Miquelón (Francia)", "searchTerm": "San Pedro y Miquelón (Francia)" },
    { "value": "206", "displayLabel": "Santa Helena (RU)", "optionLabel": "Santa Helena (RU)", "searchTerm": "Santa Helena (RU)" },
    { "value": "207", "displayLabel": "Santa Lucia", "optionLabel": "Santa Lucia", "searchTerm": "Santa Lucia" },
    { "value": "208", "displayLabel": "San Vicente y las Granadinas", "optionLabel": "San Vicente y las Granadinas", "searchTerm": "San Vicente y las Granadinas" },
    { "value": "209", "displayLabel": "Sao Tome y Principe", "optionLabel": "Sao Tome y Principe", "searchTerm": "Sao Tome y Principe" },
    { "value": "210", "displayLabel": "Senegal", "optionLabel": "Senegal", "searchTerm": "Senegal" },
    { "value": "211", "displayLabel": "Serbia", "optionLabel": "Serbia", "searchTerm": "Serbia" },
    { "value": "212", "displayLabel": "Seychelles", "optionLabel": "Seychelles", "searchTerm": "Seychelles" },
    { "value": "213", "displayLabel": "Sierra Leona", "optionLabel": "Sierra Leona", "searchTerm": "Sierra Leona" },
    { "value": "214", "displayLabel": "Singapur", "optionLabel": "Singapur", "searchTerm": "Singapur" },
    { "value": "215", "displayLabel": "Siria", "optionLabel": "Siria", "searchTerm": "Siria" },
    { "value": "216", "displayLabel": "Somalia", "optionLabel": "Somalia", "searchTerm": "Somalia" },
    { "value": "217", "displayLabel": "Sri Lanka", "optionLabel": "Sri Lanka", "searchTerm": "Sri Lanka" },
    { "value": "218", "displayLabel": "Suazilandia", "optionLabel": "Suazilandia", "searchTerm": "Suazilandia" },
    { "value": "219", "displayLabel": "Sudáfrica", "optionLabel": "Sudáfrica", "searchTerm": "Sudáfrica" },
    { "value": "220", "displayLabel": "Sudán", "optionLabel": "Sudán", "searchTerm": "Sudán" },
    { "value": "221", "displayLabel": "Sudán del Sur", "optionLabel": "Sudán del Sur", "searchTerm": "Sudán del Sur" },
    { "value": "222", "displayLabel": "Suecia", "optionLabel": "Suecia", "searchTerm": "Suecia" },
    { "value": "223", "displayLabel": "Suiza", "optionLabel": "Suiza", "searchTerm": "Suiza" },
    { "value": "224", "displayLabel": "Surinam", "optionLabel": "Surinam", "searchTerm": "Surinam" },
    { "value": "225", "displayLabel": "Tailandia", "optionLabel": "Tailandia", "searchTerm": "Tailandia" },
    { "value": "226", "displayLabel": "Taiwán", "optionLabel": "Taiwán", "searchTerm": "Taiwán" },
    { "value": "227", "displayLabel": "Tanzania", "optionLabel": "Tanzania", "searchTerm": "Tanzania" },
    { "value": "228", "displayLabel": "Tayikistán", "optionLabel": "Tayikistán", "searchTerm": "Tayikistán" },
    { "value": "229", "displayLabel": "Territorio Británico del Océano Índico (RU)", "optionLabel": "Territorio Británico del Océano Índico (RU)", "searchTerm": "Territorio Británico del Océano Índico (RU)" },
    { "value": "230", "displayLabel": "Tierras Australes y Antárticas Francesas (Francia)", "optionLabel": "Tierras Australes y Antárticas Francesas (Francia)", "searchTerm": "Tierras Australes y Antárticas Francesas (Francia)" },
    { "value": "231", "displayLabel": "Timor Oriental", "optionLabel": "Timor Oriental", "searchTerm": "Timor Oriental" },
    { "value": "232", "displayLabel": "Togo", "optionLabel": "Togo", "searchTerm": "Togo" },
    { "value": "233", "displayLabel": "Tokelau (Nueva Zelanda)", "optionLabel": "Tokelau (Nueva Zelanda)", "searchTerm": "Tokelau (Nueva Zelanda)" },
    { "value": "234", "displayLabel": "Tonga", "optionLabel": "Tonga", "searchTerm": "Tonga" },
    { "value": "235", "displayLabel": "Trinidad y Tobago", "optionLabel": "Trinidad y Tobago", "searchTerm": "Trinidad y Tobago" },
    { "value": "236", "displayLabel": "Túnez", "optionLabel": "Túnez", "searchTerm": "Túnez" },
    { "value": "237", "displayLabel": "Turcos y Caicos (RU)", "optionLabel": "Turcos y Caicos (RU)", "searchTerm": "Turcos y Caicos (RU)" },
    { "value": "238", "displayLabel": "Turkmenistán", "optionLabel": "Turkmenistán", "searchTerm": "Turkmenistán" },
    { "value": "239", "displayLabel": "Turquía", "optionLabel": "Turquía", "searchTerm": "Turquía" },
    { "value": "240", "displayLabel": "Tuvalú", "optionLabel": "Tuvalú", "searchTerm": "Tuvalú" },
    { "value": "241", "displayLabel": "Ucrania", "optionLabel": "Ucrania", "searchTerm": "Ucrania" },
    { "value": "242", "displayLabel": "Uganda", "optionLabel": "Uganda", "searchTerm": "Uganda" },
    { "value": "243", "displayLabel": "Uruguay", "optionLabel": "Uruguay", "searchTerm": "Uruguay" },
    { "value": "244", "displayLabel": "Uzbekistán", "optionLabel": "Uzbekistán", "searchTerm": "Uzbekistán" },
    { "value": "245", "displayLabel": "Vanuatu", "optionLabel": "Vanuatu", "searchTerm": "Vanuatu" },
    { "value": "246", "displayLabel": "Venezuela", "optionLabel": "Venezuela", "searchTerm": "Venezuela" },
    { "value": "247", "displayLabel": "Vietnam", "optionLabel": "Vietnam", "searchTerm": "Vietnam" },
    { "value": "248", "displayLabel": "Wallis y Futuna (Francia)", "optionLabel": "Wallis y Futuna (Francia)", "searchTerm": "Wallis y Futuna (Francia)" },
    { "value": "249", "displayLabel": "Yemen", "optionLabel": "Yemen", "searchTerm": "Yemen" },
    { "value": "250", "displayLabel": "Yibuti", "optionLabel": "Yibuti", "searchTerm": "Yibuti" },
    { "value": "251", "displayLabel": "Zambia", "optionLabel": "Zambia", "searchTerm": "Zambia" },
    { "value": "252", "displayLabel": "Zimbabwe", "optionLabel": "Zimbabwe", "searchTerm": "Zimbabwe" },
    { "value": "253", "displayLabel": "Kazajistán", "optionLabel": "Kazajistán", "searchTerm": "Kazajistán" },
    { "value": "254", "displayLabel": "República de Kosovo", "optionLabel": "República de Kosovo", "searchTerm": "República de Kosovo" }

];

export const SEX_OPTIONS: { value: string; label: string; }[] = [
    {
        value: "Masculino",
        label: "Masculino"
    },
    {
        value: "Femenino",
        label: "Femenino"
    }
];

export const ROAD_OPTIONS: { value: string; label: string; }[] = [
    {
        value: "1",
        label: "Ruta 1: Piskakucho KM 82",
    },
    {
        value: "5",
        label: "Ruta 5: Chachabamba",
    }
];

export const DOCUMENT_TYPE_OPTIONS: { value: string; label: string; }[] = [
    {
        value: "3",
        label: "Pasaporte"
    },
    {
        value: "7",
        label: "D. Identidad Extranjero"
    }
];

export const TAX_ID_OPTIONS: { value: string; label: string; }[] = [
    {
        value: "1",
        label: "General"
    },
    {
        value: "2",
        label: "Estudiante pregrado"
    },
    {
        value: "3",
        label: "Menor de edad"
    }
];