name: "tuboleto-booking-ui"
services: 
  client:
    build:
      context: .
      dockerfile: development.Dockerfile
    container_name: tb-client
    environment:
      - TZ=America/Lima
    ports: 
      - "5173:5173"
    volumes:
      - type: bind
        source: .
        target: /usr/src/service
    restart: always

  